### ISSUE TITLE
dependency_update  does not update dependencies with wildcard * version

### ISSUE THREAD

**Issue by ovidiubuligan** [hashicorp/terraform-provider-helm#1052]
## Terraform version, Kubernetes provider version and Kubernetes version

```
Terraform version: 1.3.7
Helm Provider version:  2.7.1
Kubernetes version: 1.24
```
## Terraform configuration

```hcl
resource "helm_release" "prom-stack" {
    name      = "prom-stack"
    repository = "https://prometheus-community.github.io/helm-charts"
    chart     = "kube-prometheus-stack"
    namespace = "monitoring"
    dependency_update = true    # <--- when will it update dependency ?
    version = "44.3.1"

    values = "..."
```

## Question
I am using the chart `kube-prometheus-stack`  that has dependencies to other grafana helm chart. `Chart.yaml` dependencies: 
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/Chart.yaml 
```yaml
dependencies:
  - name: kube-state-metrics
    version: "4.24.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kubeStateMetrics.enabled
  - name: prometheus-node-exporter
    version: "4.8.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: nodeExporter.enabled
  - name: grafana
    version: "6.50.*"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
```

After upgrading to "44.3.1" only main chart was updated , grafana dependency didn't update at all  , inside the cluster it is still `6.50.3` instead of `6.50.7`  . 

Is this behavior because of wildcard ? How can I force update of dependency  ?
