### ISSUE TITLE
set_list produces different behavior than array defined in values.yaml

### ISSUE THREAD

**Issue by sourcehawk** [hashicorp/terraform-provider-helm#1272]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version:  1.6.2
Provider version: "~> 2"
Kubernetes version: 1.27
```

### Affected Resource(s)

- helm_release (set_list)

### Terraform Configuration Files
Relevant section displayed (two cases of set_list) with an empty array, **which is also the default value within the chart itself, meaning it should have no effect**

```hcl
resource "helm_release" "monitoring" {
  chart = "./${path.module}/charts/monitoring"
  name = "monitoring"
  namespace = local.monitoring_namespace
  create_namespace = true
  timeout = 900 # 15 minutes

  set_list {
    name = "thanos.query.extraFlags"
    value = []
  }

  set_list {
    name = "thanos.query.stores"
    value = []
  }
}
```

Values.yaml file
```yaml
thanos:
  query:
    enabled: true
    # Override default args
    extraFlags:
      []
      # Make client use TLS (internal now only works also with TLS)
      #- --grpc-client-tls-secure
      #- --endpoint=thanos-grpc.<this-cluster>.<domain>:443
      #- --endpoint=thanos-storegateway.<this-cluster>.<domain>:443
      #- --endpoint=thanos-ruler.<this-cluster>.<domain>:443
    # External store api's
    stores:
      []
      #- thanos-query.<external-cluster-1>.<domain>:443
      #- thanos-query.<external-cluster-2>.<domain>:443
```

### Debug Output
Here in the "Args" section we can see that there is a newline before the "State" section. This newline is preventing the container from starting, as it errors upon startup because of an invalid start command.

```yaml
Containers:
  query:
    Container ID:  containerd://26648b57a91e20f8f773a4d2953ab47fc70bb1b5c862d012b79599902bd2a642
    Image:         docker.io/bitnami/thanos:0.31.0-scratch-r8
    Image ID:      docker.io/bitnami/thanos@sha256:217e2d58f8b28ccf48fe75c54892c3090e6231eefd2094250d7e2012e6a0133b
    Ports:         10902/TCP, 10901/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      query
      --log.level=debug
      --log.format=logfmt
      --grpc-address=0.0.0.0:10901
      --http-address=0.0.0.0:10902
      --query.replica-label=replica
      --endpoint=dnssrv+_grpc._tcp.monitoring-thanos-storegateway.monitoring.svc.cluster.local
      
    State:          Waiting
      Reason:       CrashLoopBackOff
```

Now if I comment out the set_list fields from earlier, this newline is no longer present. Even though an empty array is also the default value in my values.yaml file.

```hcl
resource "helm_release" "monitoring" {
  chart = "./${path.module}/charts/monitoring"
  name = "monitoring"
  namespace = local.monitoring_namespace
  create_namespace = true
  timeout = 900 # 15 minutes

  #set_list {
  #  name = "thanos.query.extraFlags"
  #  value = []
  #}

  #set_list {
  #  name = "thanos.query.stores"
  #  value = [ ]
  #}
}
```
```yaml
Containers:
  query:
    Container ID:  containerd://ea082134315feb72d48150d6db3ac07da5cdf7d6c141c61a88c826e2ae4f8500
    Image:         docker.io/bitnami/thanos:0.31.0-scratch-r8
    Image ID:      docker.io/bitnami/thanos@sha256:217e2d58f8b28ccf48fe75c54892c3090e6231eefd2094250d7e2012e6a0133b
    Ports:         10902/TCP, 10901/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      query
      --log.level=debug
      --log.format=logfmt
      --grpc-address=0.0.0.0:10901
      --http-address=0.0.0.0:10902
      --query.replica-label=replica
      --endpoint=dnssrv+_grpc._tcp.monitoring-thanos-storegateway.monitoring.svc.cluster.local
    State:          Running
      Started:      Wed, 18 Oct 2023 22:02:33 +0000
```

Update: 

If I go into edit mode using kubectl edit on the pod, there seems to be an additional array element added. Again, this does **not** happen when deploying using only values.yaml file with the same values, so the behavior in set_list is **clearly not the same**.

```yaml
  containers:
  - args:
    - query
    - --log.level=info
    - --log.format=logfmt
    - --grpc-address=0.0.0.0:10901
    - --http-address=0.0.0.0:10902
    - --query.replica-label=replica
    - --endpoint=monitoring-thanos-discovery:10901
    - --endpoint=monitoring-thanos-storegateway:10901
    - --endpoint=monitoring-thanos-receive:10901
    - --endpoint=thanos-ruler-operated:10901
    - ""
```

### Expected Behavior
The set_list only creates lists and does not add anything that is not expected.

### Actual Behavior
The set_list creates an unwanted newline where it is not expected.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
