### ISSUE TITLE
How to set {} multiline string as a value?

### ISSUE THREAD

**Issue by CiucurDaniel** [hashicorp/terraform-provider-helm#1284]
## Terraform version, Kubernetes provider version and Kubernetes version

```
Terraform version: 1.6.2
Helm Provider version: 2.11.0
Kubernetes version: 1.27
```
## Terraform configuration

```hcl
resource "helm_release" "vault" {
  name      = "vault"
  chart     = local.vault_chart_path
  namespace = "vault"

  values = [
    file("./vault-values.yaml"),
    yamlencode({ chart_hash : local.chart_hash, })
  ]

  set {
    name = "server.ha.config"
    type = "string"
    value = templatefile("../helm-charts/vault-ha-config/vault-ha-config.hcl", {
      pgusername   = "someuser"
      pgpassword   = "somepassword"
      pgserverfqdn = "some server"
      pgdatabase   = "vault"
    })
  }

  depends_on = [kubernetes_manifest.vault_psql_init_job]
}
```

Values file portion which I try to overwrite:

```yaml
server:
  ha:
    enabled: true
    replicas: 1

    # config is a raw string of default configuration when using a Stateful
    # deployment. Default is to use a Consul for its HA storage backend.
    # This should be HCL.
    config: |
      ui = true

      storage "postgresql" {
        connection_url = "postgres://{pgusername}:{pgpassword}@{pgfqdn}/{pgdatabase}"
        table = "vault_kv_store"
        ha_enabled = "true"
        ha_table = "vault_ha_locks"
      }
```

## Question

As you can see under `server.ha.config` we have a HCL file.  I try to replace that config with a file that I templated (in order to add the secrets) but it fails with error:

```
Error: error getting values: failed parsing key "server.ha.config" with value ui = true                                                                 
│                                                                                                                                                         
│ storage "postgresql" {                                                                                                                                  
│   connection_url = "postgres://{pgusername}:{pgpassword}{pgserverfqdn}/{pgdatabase}"                                                                    
│   table = "vault_kv_store"                                                                                                                              
│   ha_enabled = "true"                                                                                                                                   
│   ha_table = "vault_ha_locks"                                                                                                                           
│ }    

... rest of file                                                                                
```

**How can we use `set { }` in order to set a multiline string in the values file?**
