### ISSUE TITLE
Support aws-iam-authenticator

### ISSUE THREAD

**Issue by okgolove** [hashicorp/terraform-provider-helm#133]
### Terraform Version
Terraform v0.11.8

### Affected Resource(s)
Please list the resources as a list, for example:
- helm provider

### Expected Behavior
It will be great if I'm able to work with aws-iam-authenticator in helm provider settings.
In kubeconfig it looks like this:
```
users:
- name: eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "eks"
```

### Actual Behavior
I can specify kubeconfig or client ceritificate or user/password.
