### ISSUE TITLE
postrender does not have any effect in helm_template 

### ISSUE THREAD

**Issue by RemkoMolier** [hashicorp/terraform-provider-helm#1472]
### Terraform, Provider, Kubernetes and Helm Versions
```
Terraform version: v1.9.5
Provider version: v2.15.0
Kubernetes version: N/A
```

### Affected Resource(s)

- helm_template

### Terraform Configuration Files
```hcl
data "helm_template" "cilium" {
  namespace  = "kube-system"
  name       = "cilium"
  repository = "https://helm.cilium.io"
  chart      = "cilium"
  # renovate: datasource=helm depName=cilium registryUrl=https://helm.cilium.io
  version      = "1.16.0"
  kube_version = var.kubernetes_version
  api_versions = []
  values       = [file("values.yaml")]
  postrender {
    binary_path = "${path.module}/postrender"
  }
}
```

values.yaml:
```yaml
---
ipam:
  mode: kubernetes
securityContext:
  capabilities:
    ciliumAgent: [CHOWN, KILL, NET_ADMIN, NET_RAW, IPC_LOCK, SYS_ADMIN, SYS_RESOURCE, DAC_OVERRIDE, FOWNER, SETGID, SETUID]
    cleanCiliumState: [NET_ADMIN, SYS_ADMIN, SYS_RESOURCE]
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
k8sServiceHost: localhost
k8sServicePort: 7445
kubeProxyReplacement: true
```
postrender:
```
#!/bin/bash

yq '.metadata.annotations."meta.helm.sh/release-name"="cilium" | .metadata.annotations."meta.helm.sh/release-namespace"="kube-system" | .metadata.labels."app.kubernetes.io/managed-by" = "Helm"' <&0
```

### Debug Output
N/A

### Panic Output
N/A

### Steps to Reproduce

1. `terraform plan`

### Expected Behavior
Postrender to be executed by the helm template and the output should have been adapted

### Actual Behavior
Postrender is not executed by the helm template and the output is not adapted accordingly.

### Important Factoids
N/A

### References
N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
