### ISSUE TITLE
YAML validation failing

### ISSUE THREAD

**Issue by paymog** [hashicorp/terraform-provider-helm#1617]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: Terraform v1.11.4 on darwin_arm64
Provider version: 2.17.0
Kubernetes version: 1.30
Helm version: version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.19.1"}
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```typescript
  private datadogSetup() {
    const postgresYaml = yaml.dump(
      {
        cluster_check: true,
        init_config: {
          propagate_agent_tags: true,
        },
        instances: EnvConfig.datadogDbmHosts.map((host) => {
          return {
            dbm: true,
            host,
            port: 5432,
            username: "datadog",
            password: Token.asString(process.env.DATADOG_DBM_PASSWORD),
            database_autodiscovery: {
              enabled: true,
              exclude: ["rdsadmin"],
            },
            relations: [
              {
                relation_regex: ".*",
              },
            ],
            collect_schemas: {
              enabled: true,
            },
            collect_function_metrics: true,
            collect_activity_metrics: true,
            collect_bloat_metrics: true,
            custom_queries: [
              {
                metric_prefix: "long_running_queries_3",
                query:
                  "SELECT datname, xact_start, query FROM pg_stat_activity WHERE state = 'active' and xact_start is not null and query not ilike '%vacuum%' and current_timestamp - xact_start > interval '7 minute' order by runtime desc;",
                columns: [
                  {
                    name: "db",
                    type: "tag",
                  },
                  {
                    name: "xact_start",
                    type: "gauge",
                  },
                  {
                    name: "query",
                    type: "tag",
                  },
                ],
              },
            ],
          };
        }),
      },
      { forceQuotes: true, quotingType: '"', lineWidth: 10000 }
    );
    console.log("---------------postgres yaml--------------");
    console.log(postgresYaml);
    console.log("---------------postgres yaml--------------");

    const renderedValues = ejs.render(fs.readFileSync("./values/datadog-values.yaml.ejs", "utf-8"), {
      env: EnvConfig.name,
      datadogAgentHttpTracePort: EnvConfig.datadogAgentHttpTracePort.toString(),
      isProduction,
      apiKey: Token.asString(process.env.DATADOG_API_KEY),
    });

    new Release(this, "datadog-agent", {
      chart: "datadog",
      name: "datadog",
      repository: "https://helm.datadoghq.com",
      version: "3.110.9",
      timeout: 600,
      setSensitive: [
        {
          name: "datadog.apiKey",
          value: Token.asString(process.env.DATADOG_API_KEY),
        },
        {
          name: "clusterAgent.confd.postgres\\.yaml",
          value: postgresYaml,
        },
      ],
      values: [renderedValues],
    });

    new ClusterRole(this, "datadog-agent-clusterrole", {
      metadata: {
        name: "datadog-agent",
      },
      rule: [
        {
          apiGroups: [""],
          resources: ["nodes/metrics", "nodes/spec", "nodes/stats", "nodes/proxy", "nodes/pods", "nodes/healthz"],
          verbs: ["get"],
        },
        {
          apiGroups: [""],
          resources: ["endpoints"],
          verbs: ["list"],
        },
      ],
    });
    new ClusterRoleBinding(this, "datadog-agent-clusterrole-binding", {
      metadata: {
        name: "datadog-agent",
      },
      roleRef: {
        apiGroup: "rbac.authorization.k8s.io",
        kind: "ClusterRole",
        name: "datadog-agent",
      },
      subject: [
        {
          kind: "ServiceAccount",
          name: "datadog-agent",
          namespace: "default",
        },
      ],
    });
    new ServiceAccount(this, "datadog-agent-service-account", {
      metadata: {
        name: "datadog-agent",
        namespace: "default",
      },
    });
  }

```

### Debug Output
I'm very hesitant to provide full debug output because of how many secrets it might leak. Here's a truncated version showing the issue arising in the provider: https://gist.github.com/paymog/cc39b81c99300b47d3d4be6d0e32cd18

### Steps to Reproduce
I think this using the above datadog config will reproduce this quite easily

### Expected Behavior
The yaml that's generated is valid. Pasted here as well

```
cluster_check: true
init_config:
  propagate_agent_tags: true
instances:
  - dbm: true
    host: "graph-node-serverless.cpyibfvmddkk.us-west-2.rds.amazonaws.com"
    port: 5432
    username: "datadog"
    password: "redacted"
    database_autodiscovery:
      enabled: true
      exclude:
        - "rdsadmin"
    relations:
      - relation_regex: ".*"
    collect_schemas:
      enabled: true
    collect_function_metrics: true
    collect_activity_metrics: true
    collect_bloat_metrics: true
    custom_queries:
      - metric_prefix: "long_running_queries_2"
        query: "SELECT datname, xact_start, query FROM pg_stat_activity WHERE state = 'active' and xact_start is not null and query not ilike '%vacuum%' and current_timestamp - xact_start > interval '7 minute' order by runtime desc;"
        columns:
          - name: "db"
            type: "tag"
          - name: "xact_start"
            type: "gauge"
          - name: "query"
            type: "tag"
  - dbm: true
    host: "dev-graph-node-second-3.cpyibfvmddkk.us-west-2.rds.amazonaws.com"
    port: 5432
    username: "datadog"
    password: "redacted"
    database_autodiscovery:
      enabled: true
      exclude:
        - "rdsadmin"
    relations:
      - relation_regex: ".*"
    collect_schemas:
      enabled: true
    collect_function_metrics: true
    collect_activity_metrics: true
    collect_bloat_metrics: true
    custom_queries:
      - metric_prefix: "long_running_queries_2"
        query: "SELECT datname, xact_start, query FROM pg_stat_activity WHERE state = 'active' and xact_start is not null and query not ilike '%vacuum%' and current_timestamp - xact_start > interval '7 minute' order by runtime desc;"
        columns:
          - name: "db"
            type: "tag"
          - name: "xact_start"
            type: "gauge"
          - name: "query"
            type: "tag"
```

### Actual Behavior
Looks like the provider is trying to parse the `query` as it's own yaml block or something and thus fails

### Important Factoids
Note this line in the gist `goldsky-infra-dev  2025-04-16T11:15:00.864-0500 [ERROR] provider.terraform-provider-helm_v2.17.0_x5: Response contains error diagnostic: @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/diag/diagnostics.go:58 tf_proto_version=5.6 tf_req_id=71cc137d-4541-9506-6253-e3d85ca4b2c1 tf_provider_addr=provider tf_resource_type=helm_release tf_rpc=ApplyResourceChange @module=sdk.proto diagnostic_detail="" diagnostic_severity=ERROR` which looks like the helm provider is failing.

When I switch away from `setSensitive` and put this postgres conf directly in my values.yaml file, the issue goes away. It seems that something in `setSensitive` parsing yaml doesn't like this. Note that I recently added the `custom_queries` block and that prior to that I had no issues with `setSensitive`.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
