### ISSUE TITLE
Multiple helm_repository data providers overwrite eachother

### ISSUE THREAD

**Issue by jpreese** [hashicorp/terraform-provider-helm#271]
### Terraform Version
Terraform v0.11.13
+ provider.helm v0.9.0
+ provider.kubernetes v1.6.2
+ provider.local v1.2.1
+ provider.null v2.1.1
+ provider.tls v1.2.0

### Affected Resource(s)
- helm_repository

### Terraform Configuration Files
```hcl
data "helm_repository" "incubator" {
  name = "some_chart"
  url  = "https://kubernetes-charts-incubator.storage.googleapis.com/"
}

data "helm_repository" "stable" {
  name = "another_chart"
  url  = "https://kubernetes-charts.storage.googleapis.com/"
}
```

### Expected Behavior
The repositories.yaml contains both entries.

### Actual Behavior
The repositories.yaml will only contain one of the entries.

### Steps to Reproduce

1. `terraform apply`

**Comment by rporres** [comment]
I'm afraid I don't understand very well the issue. Can you post a more detailed example/logs? I have tf files with multiple repositories working without any apparent issue, `repositories.yaml` in the `$HOME/.helm` containing multiple entries

**Comment by jpreese** [comment]
Sure, I'll get a simple scenario created and post some logs when I get to work here in a moment. In your scenario, have you started from a base `repositories.yaml`? 

It does work if the repository already exists in the `repositories.yaml` file. The problem, for me, was when it actually needed to do an add.

@sryabkov in #163 also seems to have this issue.

**Comment by jpreese** [comment]
Steps:

1. Start with the base `repositories.yaml` (from helm init --client-only) and/or just make sure that you dont already have the repository that you've defined in your provider.

Mine looks like this for this test case

```yaml
apiVersion: v1
generated: "2019-04-09T18:32:00.6458817-04:00"
repositories:
- caFile: ""
  cache: C:\Users\jreese\.helm\repository\cache\stable-index.yaml
  certFile: ""
  keyFile: ""
  name: stable
  password: ""
  url: https://kubernetes-charts.storage.googleapis.com
  username: ""
- caFile: ""
  cache: C:\Users\jreese\.helm\repository\cache\local-index.yaml
  certFile: ""
  keyFile: ""
  name: local
  password: ""
  url: http://127.0.0.1:8879/charts
  username: ""
```


2. Setup the tf configs.

Here is my entire terraform config (main.tf)

```terraform
provider "helm" {
  version            = "~> 0.9"
}

data "helm_repository" "stable" {
  name = "another_chart"
  url  = "https://kubernetes-charts.storage.googleapis.com/"
}

data "helm_repository" "incubator" {
  name = "some_chart"
  url  = "https://kubernetes-charts-incubator.storage.googleapis.com/"
}
```

3. Run `terraform apply`

The result will be that only one of them is added. Note that if you have the notepad doc open it might show both briefly, but it is then overwritten shortly after.

Running config
![image](https://user-images.githubusercontent.com/6980197/57139109-53c36080-6d82-11e9-818f-18d92806adf2.png)

Doc asks if you want to reload, upon reloading, shows the second entry:
![image](https://user-images.githubusercontent.com/6980197/57139025-24acef00-6d82-11e9-8f9d-ba73f416c5bb.png)

ANOTHER reload request:
![image](https://user-images.githubusercontent.com/6980197/57139031-2971a300-6d82-11e9-8c2f-a5f4b4f42421.png)

Final state of the config after the apply finishes:
![image](https://user-images.githubusercontent.com/6980197/57139045-2eceed80-6d82-11e9-8c64-438b647b09af.png)

TF_LOG output
https://pastebin.com/pXjBp5q8
