### ISSUE TITLE
dependency_update doesn't act as expected

### ISSUE THREAD

**Issue by IlyaKochnev** [hashicorp/terraform-provider-helm#459]
### Terraform Version
Terraform v0.12.21
+ provider.aws v2.55.0
+ provider.helm v1.1.1
+ provider.kubernetes v1.11.1
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
+ provider.vault v2.9.0

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "nginx-ingress-controller" {
  name      = "my-nginx-ingress-controller"
  chart       = "charts/my-nginx-ingress-controller"
  namespace = "kube-system"

  dependency_update = true
}
```

The Chart.yaml
```yaml
apiVersion: v1
name: my-nginx-ingress-controller
version: 1.0.0
dependencies:
  - name: nginx-ingress
    version: 1.34.3
    repository: "@stable"
```

### Debug Output
https://gist.github.com/IlyaKochnev/b239856bfb923896130119eb481f32cc

### Expected Behavior
In accordance with https://www.terraform.io/docs/providers/helm/r/release.html#dependency_update Terraform must update dependencies and successfully install the chart.

### Actual Behavior
Terraform produces the error:
```
helm_release.nginx-ingress-controller: Creating...
Error: could not find : stat : no such file or directory
  on main.tf line 97, in resource "helm_release" "nginx-ingress-controller":
  97: resource "helm_release" "nginx-ingress-controller" {
```
There is no visible signs of dependency downloading.
After `helm dep update` run manually, Terraform installs the chart without any issues.

### Steps to Reproduce
1.  Prepare a simple chart, like
```yaml
apiVersion: v1
name: my-nginx-ingress-controller
version: 1.0.0
dependencies:
  - name: nginx-ingress
    version: 1.34.3
    repository: "@stable"
```
2. Prepare a terraform code to deploy the chart with Helm, see example above
3. `terraform apply`

### Important Factoids
helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
