### ISSUE TITLE
Unable to specify multiple tags as value to be set

### ISSUE THREAD

**Issue by nandac** [hashicorp/terraform-provider-helm#461]
Hi Team,

First, let me take the opportunity to thank you for writing this provider.

I am using this provider to deploy runners in GitLab and have the need to specify multiple tags for each runner. 

I have the following snippet in my `values.yaml`.
```
runners:
    tags: tags
    protected: true
    privileged: false
    serviceAccountName: serviceAccountName
    cache:
        cacheType: s3
        cachePath: "project"
        cacheShared: false
        s3ServerAddress: s3.amazonaws.com
        s3BucketName: s3BucketName
        s3BucketLocation: s3BucketLocation
        s3CacheInsecure: false
```

In terraform, I set the value above for `runner.tags` like so:
```
set {
    name  = "runners.tags"
    value = "${var.var_one}-${local.env},${var.var_one}-${local.env}-${local.runner_suffix}"
}
```
As you can see above I am specifying two tags as comma-separated values namely:
- `${var.var_one}-${local.env}`
- `${var.var_one}-${local.env}-${local.runner_suffix}`

The terraform plan works without a hitch but when I apply I get this error:
`Error: failed parsing key "runners.tags" with value "varone-env,varone-env-suffix", key "varone-env-suffix" has no value`

I am not sure why the second tag is taken as a key when it is all part of one string that is comma-separated.

Specifying just a single tag works without issues and I believe may have to do with how the YAML is parsed when the value contains a comma.

I would like to avoid using `provisioner "local-exec"` with a helm command just to provide multiple tags.

I hope you will be able to resolve this issue by providing at least a workaround.

Thanks in advance.
