### ISSUE TITLE
Ingress left on AWS after helm_release resource destroyed

### ISSUE THREAD

**Issue by Opalo** [hashicorp/terraform-provider-helm#474]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform v0.12.24
+ provider.aws v2.52.0
+ provider.helm v1.1.1
+ provider.kubernetes v1.11.1

### Provider Version
Helm
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```
### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "graylog" {
  depends_on = [
    module.eks.ext_dns
  ]
  chart      = "stable/graylog"
  name       = "graylog"
  version    = "1.6.2"
  values     = [
    file("${path.module}/../../k8s/${local.environment}/graylog/values.yaml")
  ]
}
```

```yaml
graylog:
  rootPassword: lol
  env:
    GRAYLOG_HTTP_EXTERNAL_URI: graylog.lol.com
  image:
    repository: graylog/graylog:3.1.3
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    hosts:
      - graylog.lol.com
    extraPaths:
      - path: /*
        backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
  replicas: 1
  service:
    type: NodePort
  input:
    tcp:
      service:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
          external-dns.alpha.kubernetes.io/hostname: input.graylog.lol.com
        type: LoadBalancer
      ports:
        - name: input
          port: 12201
```
### Debug Output

Unavailable

### Panic Output

None

### Expected Behavior

After calling `terraform destroy infrastructure`, graylog (installed with `helm_release`) should be removed and the whole AWS EKS cluster should be destroyed.

### Actual Behavior
From the output of terraform I can see that `helm_release.graylog` was indeed destroyed, however `terraform destroy infrastructure` failed with: 

```
Error: Error waiting for internet gateway (igw-whatever) to detach: timeout while waiting for state to become 'detached' (last state: 'detaching', timeout: 15m0s)
```

It happened, because after removing `helm_release.graylog` there was an ALB instance left.

It all work correctly with separate steps: `terraform apply (..)` with `helm install (..)` and `helm delete (..)` with `terraform destroy (..)`

### Steps to Reproduce

It seems that it's enough to use the `helm_release.graylog` with the configuration I provided.

### Important Factoids

Running on AWS EKS.
