### ISSUE TITLE
Helm_release in terraform plan keeps showing updates

### ISSUE THREAD

**Issue by bsuchorowski** [hashicorp/terraform-provider-helm#501]
### Terraform Version and Provider Version
Terraform v0.12.24

### Provider Version
+ provider.helm v0.10.4

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "mongo" {
  repository = data.helm_repository.stable.metadata.0.name
  namespace  = "default"
  name       = "mongo"
  chart      = "mongodb-replicaset"
  version    = "3.10.1"

  values = [
    "${file("mongo-values.yaml")}"
  ]

  set {
    name  = "auth.adminPassword"
    value = "${random_password.password-for-mongo-admin.result}"
  }

  depends_on = [random_password.password-for-mongo-admin,null_resource.tiller-setup]
}
```

### Steps to Reproduce
1. `terraform plan`

### Actual Result

Terraform plan keep showing that my values section has changes event though it is identical every time.
```
 ~ resource "helm_release" "mongo" {
        chart            = "mongodb-replicaset"
        disable_webhooks = false
        force_update     = false
        id               = "mongo"
        metadata         = [
            {
                chart     = "mongodb-replicaset"
                name      = "mongo"
                namespace = "default"
                revision  = 1
                values    = <<~EOT
                    auth:
                      adminPassword: xxx
                      adminUser: spadmin
                      enabled: true
                      key: xxx
                    persistentVolume:
                      enabled: true
                    replicas: 1
                EOT
                version   = "3.10.1"
            },
        ]
        name             = "mongo"
        namespace        = "default"
        recreate_pods    = false
        repository       = "stable"
        reuse            = false
        reuse_values     = false
        status           = "DEPLOYED"
        timeout          = 300
      ~ values           = [
          - <<~EOT
                persistentVolume:
                  enabled: true

                replicas: 1

                auth:
                  enabled: true
                  adminUser: spadmin
                  key: xxx
            EOT,
          + <<~EOT
                                    persistentVolume:
                                      enabled: true

                                    replicas: 1

                                    auth:
                                      enabled: true
                                      adminUser: spadmin
                                      key: xxx
            EOT,
        ]
        verify           = false
        version          = "3.10.1"
        wait             = true

        set {
            name  = "auth.adminPassword"
            value = "xxx"
        }
    }
```
### Expected Result

Terraform plan should not show resources that has not changed.

**Comment by krzysztof-miemiec** [comment]
I see that indentation in your `values` changed. I guess that's the cause 🤔

**Comment by bsuchorowski** [comment]
I don't know where does it come from. My file does not have any additional indentation.

**Comment by bsuchorowski** [comment]
Right now I have this output. It is identical. Why does it want to modify? 

```
      ~ values           = [
          - <<~EOT
                persistentVolume:
                  enabled: true

                replicas: 1

                auth:
                  enabled: true
                  adminUser: spadmin
                  key: xxx
            EOT,
          + <<~EOT
                persistentVolume:
                  enabled: true

                replicas: 1

                auth:
                  enabled: true
                  adminUser: spadmin
                  key: xxx
            EOT,
        ]
```
