### ISSUE TITLE
repository_config_path not working while repository_username is

### ISSUE THREAD

**Issue by fiftoine** [hashicorp/terraform-provider-helm#601]
### Terraform Version and Provider Version
0.12.20
### Provider Version
1.3.2

### Affected Resource(s)
- helm_release
- helm_provider

### Terraform Configuration Files
```hcl

provider "helm" {
  version = "~> 1.3.2"
  repository_config_path = "/repository.yaml"
  kubernetes {
    ...
  }
}

resource "helm_release" "my-release" {
  name       = "my-release"
  namespace  = "my-namespace"
  repository = "https://myprivaterepo.com/" 
  chart      = "my-chart"
  version    = "1.0.0"
}

```

```yaml
# /repository.yaml
apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: myprivaterepo
  password: my-password
  url: https://myprivaterepo.com/
  username: myuser
```

### Debug Output
```
Error: looks like "https://myprivaterepo.com/" is not a valid chart repository or cannot be reached: failed to fetch https://myprivaterepo.com/index.yaml : 401 Unauthorized
```

### Expected Behavior

The Helm release should be created.

### Actual Behavior
Error is displayed with unauthorized.

When setting username and password at helm_release level, it works correctly :

```hcl
# THIS WORKS

provider "helm" {
  version = "~> 1.3.2"
  kubernetes {
    ...
  }
}

resource "helm_release" "my-release" {
  name       = "my-release"
  namespace  = "my-namespace"
  repository = "https://myprivaterepo.com/" 
  chart      = "my-chart"
  version    = "1.0.0"
  repository_username = "myuser"
  repository_password = "my-password"
}

```

Am I missing something?

### Steps to Reproduce

1. `terraform apply`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
