### ISSUE TITLE
Problem with helm when the plugin upgrade from 2.0.3 to 2.1.0 a few days ago

### ISSUE THREAD

**Issue by xiangliang1** [hashicorp/terraform-provider-helm#719]
I had been struggled with error message similar to following for a few days:
When we ran:
> terraform plan -var-file="vars/${ENV}.tfvars"
Following error show up, and program exit:
Error: error running dry run for a diff: template: workflow-dispatcher/templates/workflow-deployment.yaml:4:38: executing "workflow/templates/workflow-deployment.yaml" at <.Values.dispatcher.name>: nil pointer evaluating interface {}.name
  on main.tf line 57, in resource "helm_release" "walle-service":
  57: resource "helm_release" "walle-service" {

This error looks like a bug introduced by upgrading the plugin from 2.0.3 to 2.1.0. On 03/30/2021, all build succeeded with downloading helm plugin 2.0.3, but on about March 31, version 2.1.0 of helm plugin is downloaded, the error above shows.

Any idea if that is a bug, or what should I do to get the variable a value?

Thank you in advance.

**Comment by viceice** [comment]
Seeing this too:
```
Error: error running dry run for a diff: template: metallb/templates/speaker/secret.yaml:4:50: executing "metallb/templates/speaker/secret.yaml" at <include "common.secrets.passwords.manage" (dict "secret" (include "metallb.speaker.secretName" .) "key" (include "metallb.speaker.secretKey" .) "providedValues" (list "speaker.secretValue") "length" 256 "context" $)>: error calling include: template: metallb/charts/common/templates/_secrets.tpl:100:6: executing "common.secrets.passwords.manage" at <include "common.errors.upgrade.passwords.empty" (dict "validationErrors" $passwordValidationErrors "context" $.context)>: error calling include: template: metallb/charts/common/templates/_errors.tpl:18:48: executing "common.errors.upgrade.passwords.empty" at <fail>: error calling fail: 
PASSWORDS ERROR: you must provide your current passwords when upgrade the release
    'speaker.secretValue' must not be empty, please add '--set speaker.secretValue=$SECRETKEY' to the command. To get the current value:

        export SECRETKEY=$(kubectl get secret --namespace "metallb-system" metallb-memberlist -o jsonpath="{.data.secretkey}" | base64 --decode)


  on modules/core/metallb.tf line 8, in resource "helm_release" "metallb":
   8: resource "helm_release" "metallb" {
```

**metallb.tf**
```hcl
resource "kubernetes_namespace" "metallb_system" {
  metadata {
    name = "metallb-system"
  }
}

resource "helm_release" "metallb" {
  name      = "metallb"
  namespace = "metallb-system"

  depends_on = [
    kubernetes_namespace.metallb_system
  ]

  repository = "https://charts.bitnami.com/bitnami"
  chart      = "metallb"
  version    = "2.3.5"

  values = [
    file("${path.module}/metallb/values.yaml")
  ]
}
```

**values.yaml**
```yaml
controller:
  image:
    registry: gcr.io
    repository: bitnami-containers/metallb-controller

speaker:
  image:
    registry: gcr.io
    repository: bitnami-containers/metallb-speaker

  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: xxxxx.yy/hosted
      operator: Exists
      effect: NoSchedule

configInline:
  address-pools:
    - name: default
      protocol: layer2
      addresses:
        - 192.168.xx.xx-192.168.xx.xx
        - 192.168.xx.xx/28

    - name: ovh
      protocol: layer2
      auto-assign: false
      addresses:
        - 51.38.xx.xx/32
```
