### ISSUE TITLE
Error: chart "eks/aws-node-termination-handler" not found in https://aws.github.io/eks-charts repository

### ISSUE THREAD

**Issue by alexmnyc** [hashicorp/terraform-provider-helm#723]
```
resource "helm_release" "aws_node_termination_handler" {
  name       = "aws-node-termination-handler"
  repository = "https://aws.github.io/eks-charts"
  chart      = "eks/aws-node-termination-handler"
  namespace = var.kube_namespace
}
```

```
helm show chart  eks/aws-node-termination-handler
apiVersion: v1
appVersion: 1.12.2
description: A Helm chart for the AWS Node Termination Handler
home: https://github.com/aws/eks-charts
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
keywords:
- eks
- ec2
- node-termination
- spot
maintainers:
- email: bwagner5@users.noreply.github.com
  name: Brandon Wagner
  url: https://github.com/bwagner5
- email: jillmon@users.noreply.github.com
  name: Jillian Montalvo
  url: https://github.com/jillmon
name: aws-node-termination-handler
sources:
- https://github.com/aws/eks-charts
version: 0.14.2

```
