### ISSUE TITLE
helm_template templates only last object from a template file.

### ISSUE THREAD

**Issue by danylohetmantsev** [hashicorp/terraform-provider-helm#768]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 0.13.5
Provider version: 2.2.0
Kubernetes version: 1.19.10
```

### Affected Resource(s)

- helm_template

### Terraform Configuration Files
```hcl
data helm_template chart {
  name         = "cert-manager"
  namespace    = "test"
  repository   = "https://charts.jetstack.io"
  chart        = "cert-manager"
  version      = "v1.4.0"
  include_crds = true
  ]
}

resource local_file manifests {
  for_each = data.helm_template.chart.manifests
  filename = "${path.root}/${each.key}"
  content  = each.value
}
```

### Steps to Reproduce

1. `terraform apply`
2. Check files that were generated as output.

### Expected Behavior

templates/webhook-rbac.yaml should have multiple objects inside from here: https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/templates/webhook-rbac.yaml

### Actual Behavior

Manifest contains only one single object.
In tf state it looks the same: 
```
"templates/webhook-rbac.yaml"               = <<~EOT
            # Source: cert-manager/templates/webhook-rbac.yaml
            apiVersion: rbac.authorization.k8s.io/v1
            kind: RoleBinding
            metadata:
              name: cert-manager-webhook:dynamic-serving
              namespace: "infra"
              labels:
                app: webhook
                app.kubernetes.io/name: webhook
                app.kubernetes.io/instance: cert-manager
                app.kubernetes.io/managed-by: Helm
                app.kubernetes.io/component: "webhook"
                helm.sh/chart: cert-manager-v1.4.0
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: Role
              name: cert-manager-webhook:dynamic-serving
            subjects:
            - apiGroup: ""
              kind: ServiceAccount
              name: cert-manager-webhook
              namespace: infra
        EOT
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
