### ISSUE TITLE
Weird behavoiur with CRDs in helm_template for dep helm chart

### ISSUE THREAD

**Issue by danylohetmantsev** [hashicorp/terraform-provider-helm#782]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 0.15.3
Provider version: 2.3.0
Kubernetes version: 1.19.7
```

### Affected Resource(s)

- helm_template

### Terraform Configuration Files
```hcl
data helm_template kube_prometheus_stack {
  name                  = var.app_name
  namespace             = var.app_namespace
  repository            = local.repository_url
  chart                 = local.chart_name
  version               = local.chart_version
  include_crds          = true
  dependency_update     = true
  skip_tests            = true
  render_subchart_notes = false
  values                = [local.values]
}

resource "local_file" "kube_prometheus_stack_manifests" {
  for_each = data.helm_template.kube_prometheus_stack.manifests
  filename = "${path.root}/cluster/namespaces/default${each.key}"
  content  = each.value
}
```

### Debug Output

NOTE: In addition to Terraform debugging, please set HELM_DEBUG=1 to enable debugging info from helm.

### Steps to Reproduce

1. `terraform plan`
2. Look for empty key with ALL crds inside + other crds with correct key names.

### Expected Behavior

Empty key is not created

### Actual Behavior

Empty key result in the error message when local file tries to create a file with a name ""

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Workaround
```hcl
data helm_template kube_prometheus_stack {
  name                  = var.app_name
  namespace             = var.app_namespace
  repository            = local.repository_url
  chart                 = local.chart_name
  version               = local.chart_version
  include_crds          = true
  dependency_update     = true
  skip_tests            = true
  render_subchart_notes = false
  values                = [local.values]
}

resource "local_file" "kube_prometheus_stack_manifests" {
  for_each = { for key in keys(data.helm_template.kube_prometheus_stack.manifests) : key => key if key != "" }
  filename = "${path.root}/cluster/namespaces/default/${var.app_name}/${each.key}"
  content  = data.helm_template.kube_prometheus_stack.manifests[each.key]
}
```

It seems like the template collects all crds into one value field with empty key (maybe it comes from an old helm_release functionality.

**Comment by jrhouston** [comment]
Ah, I think I see what's going wrong here. In the helm_template data source, we rely upon a comment that is added by the template action above each manifest, and use a regex to pick it out to figure out the name of the template:

https://github.com/hashicorp/terraform-provider-helm/blob/9981e56d58f64b6ebe7919213362c6d726ee5859/helm/data_template.go#L489

However, when I run the `kube-prometheus-stack` chart through `helm template` I see that the comment is not there in the output, but is in fact in an empty YAML document above it:

```yaml
---
# Source: crds/crd-alertmanagerconfigs.yaml
# https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.50.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: alertmanagerconfigs.monitoring.coreos.com
  # etc... 
```

The data source splits the output of `helm template` into individual documents (i.e using the `---` delimiter). So because there's no `Source: ...` comment for the CRDs in the individual document, it ends up being an empty string which is why they seem to be getting collected under the key `""`. 

Looking at the source for the chart I see that there is a comment at the top of each CRD and then the CRD is delimited as a new document here, which is likely what's causing the problem here. 

https://github.com/prometheus-community/helm-charts/blob/5969b84b6737a84e9f3aa2f91787e248c5f83d38/charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml#L1-L5

It also looks as though there is a different code path in helm when using the `--include-crds` flag when using template, that doesn't seem to add the comment above each individual CRD. Rather, it does it once for the whole file and doesn't take into account multiple manifests being in the file – which is technically the case for the file above. 

https://github.com/helm/helm/blob/699ea6dcef302d7ded608bc8a1ab6c404de81685/pkg/action/action.go#L187


So the easy fix here would be to just remove the top comment and `---` from the template in this chart, but to fix the real problem here we will need to open a PR against helm itself to have it chunk the CRD template file into individual manifests and add the `Source: ...` comment to each one. This isn't something we can easily fix on the provider side because we just get the `helm template` output back as one big plaintext string and rely upon the comment to tell us which file each manifest came from. 

A more robust thing to do on the Terraform provider side might be to not rely on the `Source: ...` comment, and instead use some combination of the apiVersion/kind/name/namespace as keys in the `manifests` map. This however would be a breaking change unless we added a new attribute that did this.

**Comment by danylohetmantsev** [comment]
@jrhouston thanks a lot for the response! i will share it with my team and we will maybe do the PR to the helm.

**Comment by phillebaba** [comment]
I am seeing similar issues with the Velero helm chart. The issues I am seeing are derived from `SplitManifests` in the helm releaseutil package.
https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/pkg/releaseutil/manifest.go#L39

I am writing some tests for regression purposes and this is the output that I am seeing.
```yaml
---
# Source: crds/first.yaml

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: firsts.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
  scope: Namespaced
  names:
    plural: firsts
    singular: first
    kind: First
```

So when it splits on `---` you end up with one empty map entry and one with the manifests that does not have a key. I guess the solution is to look at how to properly split the mulitpart manifests or get the CRDs in another method. What I do not understand however is why this is not an issue for templates.
