### ISSUE TITLE
Helm manifest experiment does not store Kubernetes List manifests correctly

### ISSUE THREAD

**Issue by mickeder** [hashicorp/terraform-provider-helm#790]
### Terraform, Provider, Kubernetes and Helm Versions
```
Terraform version: 1.0.4
Provider version: 2.3.0
Kubernetes version: 1.21.0
```

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
...
resource "helm_release" "argo_cd" {
  name       = "argo-cd"
  repository = "https://argoproj.github.io/argo-helm"
  chart      = "argo-cd"
  version    = "3.26.3"
  namespace  = "argo-cd"
  values = [
    "${file("values.yaml")}"
  ]
}
...
```
values.yaml
```
server:
  additionalProjects:
  - name: devops
    description: DevOps resources
    sourceRepos:
      - "*"
    destinations:
      - namespace: "*"
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
  additionalApplications:
  - name: apps
    project: devops
    source:
      repoURL: ...
      targetRevision: master
      path: apps
    destination:
      name: in-cluster
      namespace: argo-cd
    syncPolicy:
      automated: {}
```

### Steps to Reproduce
Use any chart with several `List` manifests, e.g. [argo-cd](https://github.com/argoproj/argo-helm/blob/argo-cd-3.26.3/charts/argo-cd/templates/argocd-configs/applications.yaml) or [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-19.2.2/charts/kube-prometheus-stack/templates/prometheus/podmonitors.yaml) official charts.

### Expected Behavior
All resulting manifests from Kubernetes `List` should be stored separately

### Actual Behavior
If a chart contains more than one Kubernetes `List` resource, all of them are stored with the same key `list/v1/`.

### Additional information
@jrhouston The problem is related to the way each manifest's [key is generated](https://github.com/hashicorp/terraform-provider-helm/blob/v2.3.0/helm/manifest_json.go#L41-L43).
`List` resource does not have a name or namespace specified, so the resulting key is always `list/v1/`. Possible solution: iterate through all underlying manifests in a list, and store them separately.

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
