### ISSUE TITLE
error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type

### ISSUE THREAD

**Issue by gothrek22** [hashicorp/terraform-provider-helm#838]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 1.1.7
Provider version: 2.4.1
Kubernetes version: 1.20
```

### Affected Resource(s)

- helm_release
- helm_repository

### Terraform Configuration Files
```hcl
resource "kubernetes_namespace" "cluster-autoscaler" {
  count = var.ca_arn == null ? 0 : 1
  metadata {
    name = "cluster-autoscaler"
  }
}

resource "helm_release" "cluster-autoscaler" {
  count     = var.ca_arn == null ? 0 : 1
  name      = "cluster-autoscaler"
  namespace = "cluster-autoscaler"

  repository = "https://kubernetes.github.io/autoscaler"
  chart      = "cluster-autoscaler"

  values = ["ca-values.yml"]

  set {
    name  = "autoDiscovery.clusterName"
    value = var.cluster_name
  }
  set {
    #escapes required to break interpolation of fields for domain style annotations
    name  = "rbac.serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    value = var.ca_arn
  }
  set {
    name  = "awsRegion"
    value = var.region
  }
}
```

ca-values.yaml:
```yaml
extraArgs:
  logtostderr: true
  stderrthreshold: info
  v: 4
  skip-nodes-with-local-storage: false
  expander: least-waste
  balance-similar-node-groups: true  
  skip-nodes-with-system-pods: false 
rbac:
  create: true
  pspEnabled: false
  serviceAccount:
    create: true
    name: cluster-autoscaler
replicaCount: 1
resources: 
  limits:
    cpu: 100m
    memory: 600Mi
  requests:
    cpu: 100m
    memory: 600Mi
securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  fsGroup: 65534
```

tfvars

### Debug Output
Nothing related could be found in the log.

### Panic Output
No panic was found

### Steps to Reproduce
1. `terraform apply`

set:

ca_arn: to any string
region: set it to any valid aws region or probably anything at all
cluster-name: set it to anything

### Expected Behavior
cluster-autoscaler should be deployed

### Actual Behavior
```
 ---> error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type map[string]interface {} ca-values.yml
│
│   helm_release.cluster-autoscaler[0],
```

### Important Factoids
AWS EKS is used here.

If I disable values attribute and run an apply, it works, enabling values attribute then and re-running also works. It only fails when running against a vanilla setup

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
