### ISSUE TITLE
cannot unmarshal bool into Go struct field ObjectMeta.metadata.annotations of type string

### ISSUE THREAD

**Issue by nomopo45** [hashicorp/terraform-provider-helm#898]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: Terraform v1.1.5
Provider version: helm v2.6.0
Kubernetes version: last one
```

## My terraform file:

```
resource "kubernetes_namespace" "namespace" {
  metadata {
    name = var.namespace
  }
}

resource "helm_release" "HelmInstall" {
  depends_on = [kubernetes_namespace.namespace]
  name       = var.name
  repository = "s3://${var.helm_bucket_name}/charts/"
  chart      = var.chart
  version    = var.chart-version
  namespace  = var.namespace
  timeout    = 900

  values = [
    data.template_file.values.rendered
  ]
}

data "template_file" "values" {
  template = <<EOF
  zones: 
    ${var.zones}
  name: ${var.sc_name}
  type: ${var.type}
  defaultclass: ${var.default-class}
  provisioner: ${var.provisioner}
  reclaimPolicy: ${var.reclaimPolicy}
EOF  
}
```

## My helm chart :

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.name }}
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: {{ .Values.defaultclass }}
parameters:
  type: {{ .Values.type }}
provisioner: {{ .Values.provisioner }}
allowVolumeExpansion: true
reclaimPolicy: {{ .Values.provisioner }}
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values: 
      {{ .Values.zones | toYaml | indent 4 }}
```

## The error : 

```
 # helm_release.HelmInstall will be created
  + resource "helm_release" "HelmInstall" {
      + atomic                     = false
      + chart                      = "storageclass"
      + cleanup_on_fail            = false
      + create_namespace           = false
      + dependency_update          = false
      + disable_crd_hooks          = false
      + disable_openapi_validation = false
      + disable_webhooks           = false
      + force_update               = false
      + id                         = (known after apply)
      + lint                       = false
      + manifest                   = (known after apply)
      + max_history                = 0
      + metadata                   = (known after apply)
      + name                       = "gp3elk"
      + namespace                  = "elk"
      + pass_credentials           = false
      + recreate_pods              = false
      + render_subchart_notes      = true
      + replace                    = false
      + repository                 = "s3://xxxxxxxxxxxxxxxxxx/charts/"
      + reset_values               = false
      + reuse_values               = false
      + skip_crds                  = false
      + status                     = "deployed"
      + timeout                    = 900
      + values                     = [
          + <<-EOT
                  zones:
                    - "eu-west-3a"

                  name: gp3elk
                  type: gp3
                  defaultclass: false
                  provisioner: ebs.csi.aws.com
                  reclaimPolicy: Delete
            EOT,
        ]
      + verify                     = false
      + version                    = "2.3.3"
      + wait                       = true
      + wait_for_jobs              = false
    }

Plan: 1 to add, 0 to change, 0 to destroy.

helm_release.HelmInstall: Creating...
╷
│ Error: unable to build kubernetes objects from release manifest: unable to decode "": json: cannot unmarshal bool into Go struct field ObjectMeta.metadata.annotations of type string
│
│   with helm_release.HelmInstall,
│   on helm.tf line 7, in resource "helm_release" "HelmInstall":
│    7: resource "helm_release" "HelmInstall" {
│
╵
ERRO[0015] 1 error occurred:
	* exit status 1
```

As you can see i'm having an error when i just do a helm install using the following values :
```
zones:
  - "eu-west-3a"
name: "gp3elk"
type: "gp3"
defaultclass: false
provisioner: "ebs.csi.aws.com"
reclaimPolicy: "Delete"
```

it's working but when i use terraform it is not do you have an idea what is the problem ?
