### ISSUE TITLE
`nil pointer` error when the if statement evaluate the missing "key"

### ISSUE THREAD

**Issue by chrisduong** [hashicorp/terraform-provider-helm#905]
### Terraform, Provider, Kubernetes and Helm Versions

The error happens when the Helm template `if` statement evaluate the missing "key" ( it's the _override_ key in this case)

```yaml
initContainers:
      - name: aws-vpc-cni-init
        image: "{{- if .Values.init.image.override }}{{- .Values.init.image.override }}{{- else }}{{- .Values.init.image.account }}.dkr.ecr.{{- .Values.init.image.region }}.{{- .Values.init.image.domain }}/amazon-k8s-cni-init:{{- .Values.init.image.tag }}{{- end}}"
```

```
Terraform version: v1.2.3
Provider version:  v2.6.0
Kubernetes version: 1.22.9
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
namespace = "kube-system"

  name       = "aws-vpc-cni"
  repository = "https://aws.github.io/eks-charts"
  chart      = "aws-vpc-cni"
  version    = "1.1.17"

  set {
    name  = "wait"
    value = var.wait_for_helm_release
  }
}
```

Default Chart values for reference:

```
init:
  image:
    tag: v1.11.2
    region: us-west-2
    account: "602401143452"   
    pullPolicy: Always
    domain: "amazonaws.com"  
```

### Debug Output

```
Error: template: aws-vpc-cni/templates/daemonset.yaml:65:32: executing "aws-vpc-cni/templates/daemonset.yaml" at <.Values.image.override>: nil pointer evaluating interface {}.override
```

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior

Helm rendered the templates successfully. It actually works with Helm 3.

### References

- GH-1234

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
