### ISSUE TITLE
Terraform plans on namespace change even though it should force replacement

### ISSUE THREAD

**Issue by jalaziz** [hashicorp/terraform-provider-helm#967]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 1.2.9
Provider version: 2.7.0
Kubernetes version: 1.21
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
variable "metrics_server_replicas" {
  type        = number
  description = "The number of replicas for the metrics server."
  default     = 2
  nullable    = false
}

resource "helm_release" "metrics-server" {
  name             = "metrics-server"
  repository       = "https://kubernetes-sigs.github.io/metrics-server"
  chart            = "metrics-server"
  namespace        = "kube-system"
  version          = "3.8.2"
  create_namespace = false

  values = [
    templatefile("${path.module}/values/metrics-server.yaml.tftpl", {
      high_availability = (var.metrics_server_replicas > 1)
    })
  ]

  set {
    name  = "replicas"
    value = var.metrics_server_replicas
  }
}
```

```yaml
%{ if high_availability ~}
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1

podDisruptionBudget:
  # https://kubernetes.io/docs/tasks/run-application/configure-pdb/
  enabled: true
  minAvailable: 1
%{ endif ~}

service:
  labels:
    #  Add these labels to have metrics-server show up in `kubectl cluster-info`
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Metrics-server"

resources:
  #  See https://github.com/kubernetes-sigs/metrics-server#scaling
  requests:
    cpu: 100m
    memory: 200Mi
```

### Debug Output

https://gist.github.com/jalaziz/32a0bbfdd669db25df6d3a465833d58a

### Steps to Reproduce

1. `terraform plan`

### Expected Behavior

Since a namespace change requires replacement (`ForceNew` is `true`), the plan should indicate an uninstall and re-install of the helm chart.

### Actual Behavior

The plan seems to try and generate an update diff which fails with an error because helm doesn't allow namespace changes.

The error received is:
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "system:metrics-server-aggregated-reader" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "kube-system": current value is "metrics-server"
```

### Important Factoids

The actual workspace contains more resources, but the error is specific to a change in a single helm release.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
